workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
      variables: 
        PARENT_WORKFLOW: 'review'
    - if: $CI_COMMIT_BRANCH && $CI_OPEN_MERGE_REQUESTS && $CI_PIPELINE_SOURCE != 'web'
      when: 'never'
    - if: $CI_COMMIT_BRANCH
      variables: 
        PARENT_WORKFLOW: 'standart'

trigger_job:
  variables:
    PARENT_WORKFLOW: $CI_PIPELINE_SOURCE
  trigger:
    project: sig/ed/rtge/MapStoreExtension
    branch: rm/CI

#build:
#    stage: build
#    image: node:20-bookworm
#    script: 
#        - npm run ext:build
