workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
    - if: $CI_PIPELINE_SOURCE != 'merge_request_event' && $PREVENT_PIPELINES != '1'

trigger_job:
  trigger:
    project: sig/ed/rtge/MapStoreExtension
    branch: rm/CI

#build:
#    stage: build
#    image: node:20-bookworm
#    script: 
#        - npm run ext:build
